apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: azure-live 
  janus-idp.io/tekton: azure-live
  backstage.io/kubernetes-id: azure-live
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: azure-live
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml