apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: azure-live
  janus-idp.io/tekton: azure-live
  backstage.io/kubernetes-id: azure-live
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: azure-live
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
