apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: azure-live
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: azure-live 
  name: azure-live
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: azure-live 
